### PR TITLE
Update test

### PR DESCRIPTION
**Pull request by Omerrit**
fix package name for work test

### CODE REVIEW

**Comment by andyone** [comment]
Could you please explain what type of problems do you have with pkg.re service?

**Comment by Omerrit** [comment]
go mod tidy ->

go: gitlab.ozon.ru/travel/railway-api/internal/service imports
        gitlab.ozon.ru/travel/go-suggestion/location imports
        github.com/essentialkaos/translit tested by
        github.com/essentialkaos/translit.test imports
        pkg.re/check.v1: pkg.re/check.v1@v0.0.0-20201130134442-10cb98267c6c: parsing go.mod:
        module declares its path as: gopkg.in/check.v1
                but was required as: pkg.re/check.v1
```

**Comment by Omerrit** [comment]
So, if i use this lib go mod cant find pkg.re/check.v1 and go get don't working

**Comment by andyone** [comment]
I have released version 2.0.2 with go modules compatibility fixes. Just do `go get -v -d -u pkg.re/essentialkaos/translit.v2` and after update `go mod tidy` should work without any errors.

**Pull request closed without merging**
